name: ReadiumBook
options:
  bundleIdPrefix: com.zodinplex.book
packages:
  Readium:
    url: https://github.com/readium/swift-toolkit.git
    version: 2.3.0
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    from: 5.8.0
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    from: 5.15.8
  MBProgressHUD:
    url: https://github.com/jdg/MBProgressHUD.git
    from: 1.2.0
  SwiftSoup:
    url: https://github.com/scinfu/SwiftSoup.git
    from: 2.3.2
  AdMob:
    url: https://github.com/googleads/swift-package-manager-google-mobile-ads.git
    from: 9.9.0
  RevenueCat:
    url: https://github.com/RevenueCat/purchases-ios.git
    version: 4.12.0
targets:
  ReadiumBook:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources: 
      - path: Sources
    dependencies:
      - package: Readium
        product: R2Shared
      - package: Readium
        product: R2Streamer
      - package: Readium
        product: R2Navigator
      - package: Readium
        product: ReadiumOPDS
      - package: GRDB
      - package: Kingfisher
      - package: MBProgressHUD
      - package: AdMob
      - package: RevenueCat

